version: '3.8'

services:
  db_diary:
    image: postgres:15
    env_file:
      - .env
    volumes:
      - diary_db_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  web_diary:
    image: natsha014/web_diary:latest
    command: bash -c "python manage.py migrate && python manage.py collectstatic --noinput && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
      - diary_static_volume:/code/staticfiles
    env_file:
      - .env
    depends_on:
      db_diary:
        condition: service_healthy

  nginx_diary:
    image: nginx:latest
    ports:
      - "82:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - diary_static_volume:/code/staticfiles
    depends_on:
      - web_diary

volumes:
  diary_db_data:
  diary_static_volume:
